#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs:
# - https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
# - https://intercom.help/trmnl/en/articles/10513740-custom-plugin-form-builder
#
---
name: Open-Meteo Hourly Weather Forecast
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
strategy: polling
polling_verb: get
polling_url: "https://api.open-meteo.com/v1/forecast?latitude={{lat}}&longitude={{lon}}&temperature_unit={{unit_temperature}}&daily=weather_code,sunrise,sunset,temperature_2m_max,temperature_2m_min&hourly=temperature_2m,weather_code,is_day&models=best_match&current=temperature_2m,is_day,weather_code&timezone=auto&forecast_days=3\r\nhttps://andi4000.github.io/weather-app-assets/open-meteo/descriptions.v1.json\r\nhttps://andi4000.github.io/weather-app-assets/open-meteo/iconsmapping.v1.json\r\nhttps://andi4000.github.io/weather-app-assets/i18n.json"
polling_headers: ''
refresh_interval: 15
custom_fields:
- keyname: fubar
  name: About This Plugin
  field_type: author_bio
  description: >
    Hourly weather forecast plugin with Open-Meteo Backend. No API key required.
    Click save right after plugin import, to populate the required fields to fetch the weather data.
    Otherwise you will get "Liquid error" messages.
  github_url: https://github.com/andi4000/trmnl-open-meteo-weather-forecast
- keyname: lat
  optional: false
  field_type: string
  name: Latitude
  description: Latitude of your location
  help_text: Google "lat lon &lt;city name&gt;" to find your coordinates
  placeholder: 52.52
  default: 52.52
- keyname: lon
  optional: false
  field_type: string
  name: Longitude
  description: Longitude of your location
  help_text: Google "lat lon &lt;city name&gt;" to find your coordinates
  placeholder: 13.41
  default: 13.41
- keyname: lang
  field_type: select
  name: Language
  description: Display language
  optional: false
  default: de
  options:
  - English: en
  - German: de
  - French: fr
  - Spanish: es
  - Italian: it
  - Dutch: nl
- keyname: unit_temperature
  field_type: select
  name: Temperature Unit
  description: Temperature unit to use
  optional: false
  default: celsius
  options:
  - Celsius: celsius
  - Fahrenheit: fahrenheit
- keyname: date_format_today
  field_type: string
  name: Date Format Today
  description: Format for today's date in strftime format
  help_text: See <a href="https://strftime.net/" class="underline">strftime.net</a> for details
  default: "%A, den %d.%m.%Y"
- keyname: date_format_tomorrow
  field_type: string
  name: Date Format Tomorrow
  description: Format for tomorrow's date in strftime format
  help_text: See <a href="https://strftime.net/" class="underline">strftime.net</a> for details
  default: "%A"
- keyname: disp_full_today_max_hours
  field_type: number
  name: "Full Display: Today's Max Hours"
  description: Number of hours to display for today's hourly temperature, counting from current hour. For Full and Half Horizontal Display mode.
  optional: false
  default: 7
- keyname: disp_full_tomorrow_hours
  field_type: string
  name: "Full Display: Tomorrow's Hours"
  description: Comma-separated list of hours to display for tomorrow. For Full and Half Horizontal Display mode.
  optional: false
  default: "7,9,11,13,15,17,19"
- keyname: disp_half_vertical_today_max_hours
  field_type: number
  name: "Half Vertical Display: Today's Max Hours"
  description: Number of hours to display for today's hourly temperature. For Half Vertical Display mode.
  optional: false
  default: 5
